### PR TITLE
remove numpy and pandas to be imported by default

### PR DESCRIPTION
**Pull request by semiversus**
Solves issue #5

### CODE REVIEW

**Comment by semiversus** [comment]
Unsure what's actually failing in CI - timeout?

**Comment by smarie** [comment]
perfect. Like for the other PR, it seems that you need to push a dummy commit in this branch in order to trigger a new build WITH the travis script modifications. Can you please have a try ? Thanks !

**Comment by semiversus** [comment]
Ok

**Comment by semiversus** [comment]
After lunch :smiley:

**Pull request merged**
